config/routes.rb
Rails.application.routes.draw do
  get 'home_pages/home'
  # devise_for :users
  devise_for :users, path: '', path_names: {
    sign_in: 'login', sign_out: 'logout',
    password: 'secret', confirmation: 'verification',
    registration: 'register', edit: 'edit/profile'
  }, sign_out_via: [:get, :post]

  resources :users, only: [:index]
  resources :groups do
    resources :entities
  end
  # Defines the root path route ("/")
  get 'home', to: 'home_pages#home'
  root "home_pages#home"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= user.new
    can :read, Entity, public: true

    return unless user.present?

    can(:read, Entity, user:)

    return unless user.admin?

    can :manage, Entity
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :user
  has_many :entity_groups, dependent: :destroy
  has_many :groups, through: :group_operations

  validates :name, :amount, presence: true
  validates :amount, numericality: { greater_than_or_equal_to: 0 }
end

app/models/entity_group.rb
class EntityGroup < ApplicationRecord
  belongs_to :entity
  belongs_to :group
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :entity_groups, dependent: :destroy
  has_many :entities, through: :entity_groups

  validates :name, :icon, presence: true

  def total_amount
    entities.sum(:amount)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :entities
  has_many :groups

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def after_sign_in_path_for(_)
    groups_path
  end

  def after_sign_up_path_for(_)
    new_user_path
  end

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :set_entity, only: %i[show edit update destroy]

  def index
    @group_id = params[:group_id]
    @entities = Entity.all
  end

  def new
    @group_id = params[:group_id]
    @entity = Entity.new
  end

  def show
    @group = Group.find(params[:group_id])
  end

  def edit
    @group = Group.find(params[:group_id])
    @entity = Entity.find(params[:id])
  end

  def create
    @user = current_user
    @entity = Entity.new(entity_params)
    @entity.user_id = @user.id

    if @entity.save
      @group_id = params[:group_id]
      @entity_group = EntityGroup.new(entity_id: @entity.id, group_id: @group_id)

      if @entity_group.save
        redirect_to group_url(@group_id), notice: 'Entity was successfully created.'
      else
        flash[:alert] = 'Entity Group couldn`t be saved'
        redirect_to new_group_entity_url(@group_id)
      end
    else
      flash[:alert] = 'Transaction couldn`t be saved, please check name and amount'
      @group_id = params[:group_id]
      redirect_to new_group_entity_url(@group_id)
    end
  end

  def update
    @group = Group.find(params[:group_id])
    @entity = Entity.find(params[:id])

    respond_to do |format|
      if @entity.update(entity_params)
        format.html { redirect_to entity_url(@entity), notice: 'Entity was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @group = Group.find(params[:group_id])
    @entity.destroy

    respond_to do |format|
      format.html { redirect_to group_url(@group), notice: 'Transaction was successfully destroyed.' }
    end
  end

  private

  def set_entity
    @entity = Entity.find(params[:id])
  end

  def entity_params
    params.require(:entity).permit(:name, :amount)
  end
end

app/controllers/entity_groups_controller.rb
class EntityGroupsController < ApplicationController
  before_action :set_entity_group, only: %i[show edit update destroy]

  # GET /entity_groups or /entity_groups.json
  def index
    @entity_groups = EntityGroup.all
  end

  # GET /entity_groups/1
  def show; end

  # GET /entity_groups/new
  def new
    @entity_group = EntityGroup.new
  end

  # GET /entity_groups/1/edit
  def edit; end

  # POST /entity_groups
  def create
    @entity_group = EntityGroup.new(entity_group_params)

    respond_to do |format|
      if @entity_group.save
        format.html { redirect_to group_entity_url(@entity_group), notice: 'Group entity was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entity_groups/1
  def update
    respond_to do |format|
      if @entity_group.update(entity_group_params)
        format.html { redirect_to group_entity_url(@entity_group), notice: 'Group entity was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entity_groups/1
  def destroy
    @entity_group.destroy

    respond_to do |format|
      format.html { redirect_to group_entities_url, notice: 'Group entity was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_entity_group
    @entity_group = EntityGroup.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def entity_group_params
    params.fetch(:entity_group, {})
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]

  def index
    @user = current_user
    @groups = Group.where(user_id: @user.id).includes(:entity_groups)
  end

  def show
    @group = Group.find(params[:id])
    @entities = @group.entities.order(created_at: :desc)
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.user_id = current_user.id

    respond_to do |format|
      if @group.save
        format.html { redirect_to group_url(@group), notice: 'Category was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_url(@group), notice: 'Category was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Category was successfully destroyed.' }
    end
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/home_pages_controller.rb
class HomePagesController < ApplicationController
  def home; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  # def show
  #   if user_signed_in?
  #     @user = User.find(params[:id])
  #   else
  #     redirect_to new_user_session_path
  #   end
  # end

  # def new
  #   @user = User.new
  # end

  # def create
  #   @user = User.new(user_params)
  #   if @user.save
  #     redirect_to new_user_path
  #   else
  #     render 'new'
  #   end
  # end

  # def edit
  #   @user = User.find(params[:id])
  # end

  # def update
  #   @user = User.find(params[:id])

  #   if @user.update(user_params)
  #     redirect_to @user, notice: "User was successfully updated."
  #   else
  #     render :edit
  #   end
  # end

  # def destroy
  #   @user = User.find(params[:id])
  #   @user.destroy

  #   redirect_to users_url, notice: "User was successfully deleted."
  # end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entities_groups_helper.rb
module EntitiesGroupsHelper
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/helpers/entity_groups_helper.rb
module EntityGroupsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_pages_helper.rb
module HomePagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/entities/_entity.html.erb
<div class="entity-row" id="<%= dom_id entity %>">
  <p>
    <strong>Name:</strong>
    <%= entity.name %>
  </p>

  <p>
    <strong>Transaction #</strong>
    <%= entity.id %>
  </p>

  <p>
    <strong>Created At</strong>
    <%= entity.created_at %>
  </p>

  <p>
    <strong>TOTAL PAYMENT:</strong>
    $<%= entity.amount %>
  </p>

</div>

app/views/entities/_form.html.erb
<%= form_with(model: entity, url: group_entities_path, method: :post) do |form| %>
  <% if entity.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(entity.errors.count, "error") %> prohibited this entity from being saved:</h2>

      <ul>
        <% entity.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class='entity-form'>
    <%= form.text_field :name, placeholder: 'Name' %>
  </div>

  <div class='entity-form'>
    <%= form.number_field :amount %>
  </div>
  
  <br>

  <div class='entity-form btn-bottom'>
    <%= form.submit %>
  </div>
<% end %>

app/views/entities/index.html.erb
<div id="entities">
  <% @entities.each do |entity| %>
    <%= render entity %>
    <p>
      <%= link_to "Show this entity", group_entities_path(entity.id) %>
    </p>
  <% end %>
</div>

<%= link_to "New entity", new_entity_path %>

app/views/entities/new.html.erb
<nav class="group-header"> 
  <%= link_to "BACK", group_url(@group_id), class: "link-header" %>
  <p class="header-title">New Transaction</p>
  <p></p>
</nav>

<%= render "form", entity: @entity %>

app/views/entities/show.html.erb
<nav class="group-header"> 
  <%= link_to "BACK", group_path(@group), class: "link-header" %>
  <p class="header-title">Details</p>
  <%= button_to "REMOVE", @entity_group, method: :delete, class: "btn-header" %>
</nav>

<%= render @entity %>

app/views/entity_groups/_entity_group.html.erb
<div id="<%= dom_id entity_group %>">
</div>

app/views/entity_groups/_form.html.erb
<%= form_with(model: @entity, url: group_entities_path, method: :post) do |form| %>
  <% if entity_group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(entity_group.errors.count, "error") %> prohibited this entity_group from being saved:</h2>

      <ul>
        <% entity_group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/entity_groups/index.html.erb
<h1>Entity groups</h1>

<div id="entity_groups">
  <% @entity_groups.each do |entity_group| %>
    <%= render entity_group %>
    <p>
      <%= link_to "Show this entity group", group_entity %>
    </p>
  <% end %>
</div>

<%= link_to "New entity group", new_group_group_entity_path %>

app/views/entity_groups/new.html.erb
<h1>New transaction</h1>

<%= render "form", entity_group: @entity_group %>

<br>

<div>
  <%= link_to "Back to category", groups_path %>
</div>

app/views/entity_groups/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @entity_group %>

<div>
  <%= link_to "Edit this group entity", edit_group_entity_path(@entity_group) %> |
  <%= link_to "Back to group entities", group_entities_path %>
  <%= button_to "Destroy this group entity", @entity_group, method: :delete %>
</div>

app/views/groups/_form.html.erb
<%= form_with(model: group) do |form| %>
  <% if group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class= 'group-form'>
    <%= form.text_field :name, placeholder: 'Name' %>
  </div>

  <div class= 'group-form'>
    <%= form.text_field :icon, placeholder: 'Icon Link' %>
  </div>

  <div class="group-form btn-bottom">
    <%= form.submit %>
  </div>
<% end %>

app/views/groups/_group.html.erb
<div class="group-item" id="<%= dom_id group %>">
  <img class="group-image" src="<%= group.icon %>" alt=<%= group.name %>/>
  <div class="group-details">
    <p>
      <%= group.name %>
    </p>

    <p>
      $<%= group.total_amount %>
    </p>
  </div>
</div>

app/views/groups/index.html.erb
<section class="group">
  <% if user_signed_in? %>
    <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
  <% end %>
  <p class="header-title">CATEGORIES</p>
  <div class="group-container" id="groups">
    <% @groups.each do |group| %>
      <%= link_to group_path(group.id), class: "group-link" do %>
        <%= render group %>
      <% end %>
    <% end %>
  </div>

  <div class="group-footer">
    <%= link_to "ADD CATEGORY", new_group_path, class: "btn-bottom" %>
  </div>
</section>

app/views/groups/new.html.erb
<nav class="group-header"> 
  <%= link_to "BACK", groups_path, class: "link-header" %>
  <p class="header-title">New category</p>
</nav>

<%= render "form", group: @group %>

app/views/groups/show.html.erb
<nav class="group-header"> 
  <%= link_to "BACK", groups_path, class: "link-header" %>
  <%= button_to "REMOVE", @group, method: :delete, class: "btn-header" %>
</nav>

<%= render @group %>

<div class="entities-container">
  <% @entities.each do |entity| %>
    <%= link_to group_entity_path(@group.id, entity.id), class: "group-link" do %>
      <div class="entities-item">
        <div class="entity-info">
          <p><%= entity.name %></p>
          <p><%= entity.created_at %></p>
        </div>
        <p>$<%= entity.amount %></p>
      </div>
    <% end %> 
  <% end %> 
</div>

<div>
  <%= button_to "ADD TRANSACTION", new_group_entity_path(@group.id), method: :get, class: "btn-bottom" %>
</div>

app/views/home_pages/home.html.erb
<section id='home_page'>
  <h2 class='home_page'>CashControl</h2>
  <div class='log_btn'>
    <button class='btn login_btn'>
      <%= link_to 'LOG IN', new_user_session_path %>
    </button>

    <button class='btn signup_btn'>
      <%= link_to 'SIGN UP', new_user_registration_path %>
    </button>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h1>Hi! I am from index view</h1>

app/views/users/new.html.erb
<h1>I was just created</h1>

app/views/users/show.html.erb
<h2>This is User show action page</h2>